# Generated by Django 4.2.7 on 2024-06-05 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=4.0)),
                ('header', models.IntegerField(default=0, null=True)),
                ('previous_hash', models.CharField(max_length=200, null=True)),
                ('hash_blockchain', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 36, 0, 777580, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.TextField(max_length=2000)),
                ('address_wallet', models.CharField(default='c10a76527b7a4fb89c98c08f14afa97e', max_length=200, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 36, 0, 778306), null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 36, 0, 778335), null=True)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 36, 0, 778368), null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.IntegerField(default=0, null=True)),
                ('from_send', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('from_key', models.CharField(default='45590094450241e8b91422195fed1026', max_length=200)),
                ('destination_key', models.CharField(default='bc30dff27ba64125899c38c0714e6042', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 36, 0, 776740, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
