# Generated by Django 4.2.7 on 2024-11-20 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=4.0)),
                ('header', models.IntegerField(default=0, null=True)),
                ('previous_hash', models.CharField(max_length=200, null=True)),
                ('hash_blockchain', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 0, 57, 900261, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password1', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('address_wallet', models.CharField(max_length=200)),
                ('balance', models.FloatField(default=0)),
                ('phone', models.IntegerField(unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 0, 57, 900742), null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 0, 57, 900780), null=True)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 0, 57, 900802), null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.IntegerField(default=0, null=True)),
                ('from_send', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('from_key', models.CharField(default='05a2d2c315a14720b1692432065811c0', max_length=200)),
                ('destination_key', models.CharField(default='3936511e151b4173b7fe8a77dcc79bef', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 0, 57, 899740, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('phone', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('address_wallet', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
