# Generated by Django 4.2.7 on 2025-03-07 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='liked_users',
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 0, 50, 33, 51480, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 0, 50, 33, 53079), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 0, 50, 33, 53139), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 0, 50, 33, 53112), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 0, 50, 33, 50561, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
