# Generated by Django 4.1 on 2023-10-04 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockchains",
            name="data",
        ),
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 49, 10, 861981), null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 49, 10, 860914), null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="8a75df7f18bf4b5a876bbc57a3688129", max_length=500, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="8491ad428d744568affe4561301bf46d", max_length=500, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="ec5ee8bfcbc34f40af626283c197ebba", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 49, 10, 861981), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 49, 10, 861981), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 49, 10, 861981), null=True
            ),
        ),
    ]
