# Generated by Django 4.2.7 on 2025-03-08 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_new_liked_users_alter_blockchains_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_key',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_key',
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 16, 21, 704575, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 16, 21, 706265), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 16, 21, 706345), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 16, 21, 706311), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 16, 21, 704042, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_send',
            field=models.CharField(max_length=500),
        ),
    ]
