# Generated by Django 4.1 on 2023-10-04 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_remove_blockchains_data_alter_blockchains_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 54, 37, 895532), null=True
            ),
        ),
        migrations.AlterField(
            model_name="blockchains",
            name="hash_blockchain",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="blockchains",
            name="previous_hash",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 54, 37, 895532), null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="a21ce77c9e5341e4925c43abd3d9e4bf", max_length=500, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="65cb71569f724e6f8eff6c86ab4e2f69", max_length=500, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="c6ebdb539b4d4c27875a1bd442cbe301", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 54, 37, 895532), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 54, 37, 895532), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 1, 54, 37, 895532), null=True
            ),
        ),
    ]
