# Generated by Django 4.2.7 on 2025-03-31 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_transaction_destination_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 21, 32, 817002, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='hash_blockchain',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='previous_hash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 21, 32, 818980), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 21, 32, 819056), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 21, 32, 819021), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 21, 32, 816485, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
