# Generated by Django 4.1 on 2023-10-04 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_blockchains_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 8, 50, 33, 424856), null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 8, 50, 33, 423943), null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="83f412c2f090472d9817fc42e4d400fd", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="9b8a8ff91e2f49feac4e226a4b512721", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="3f8302c8bc4a4c15b9910c218042dc3e", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 8, 50, 33, 424856), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 8, 50, 33, 424856), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 8, 50, 33, 424856), null=True
            ),
        ),
    ]
