# Generated by Django 4.2.7 on 2024-12-06 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_new_titlepage_alter_blockchains_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='liked_users',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 2, 11, 2, 887854, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 2, 11, 2, 888317), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 2, 11, 2, 888430), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 2, 11, 2, 888383), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 2, 11, 2, 887056, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='5deb0e86efa346cca6612662f9c9af0e', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='8971e15f6eb041c7820f96d58b24859e', max_length=200),
        ),
    ]
