# Generated by Django 4.1 on 2023-11-02 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_blockchains_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="5dc668f3ea2945b59a390e377919f60c", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="47b7860f0e754fdbb7c43a90dcf8981e", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="bb623deb823c40de81ef5439eb513215", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 13, 6, 28, 519668), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 13, 6, 28, 519668), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 13, 6, 28, 519668), null=True
            ),
        ),
    ]
