# Generated by Django 4.1 on 2023-11-02 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_blockchains_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 15, 0, 7, 335091, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 15, 0, 7, 334090, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="a0200069938347af9acc3c1988e9c9ef", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="f02cf16ba35c4cae8ecfe6a78ccddffb", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="cd962c83fb49457cb2c5bd14a559d9fc", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 0, 7, 335091), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 0, 7, 335091), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 0, 7, 335091), null=True
            ),
        ),
    ]
