# Generated by Django 4.2.7 on 2025-01-07 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_destination_transaction_pass_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_wallet',
            field=models.CharField(default='d06da0457da24914bb9abcb6a2b407b7', max_length=200),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 18, 11, 324668, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 18, 11, 326851), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 18, 11, 326932), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 18, 11, 326905), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 18, 11, 323261, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='f66aaae6f9c342498bc5b52aa91f2db2', max_length=200),
        ),
    ]
