# Generated by Django 4.1 on 2023-11-02 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_blockchains_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockchains",
            name="nonce",
        ),
        migrations.AlterField(
            model_name="blockchains",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 15, 49, 39, 33289, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 2, 15, 49, 39, 33289, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination_key",
            field=models.CharField(
                default="a04df289a7e44149981489ffcd6790e2", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_key",
            field=models.CharField(
                default="6289392f2dc9437986157b178464485f", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_wallet",
            field=models.CharField(
                default="fc1f34b6e324427b9ae9b298f6c25fff", max_length=2000, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 49, 39, 33289), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 49, 39, 33289), null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 15, 49, 39, 33289), null=True
            ),
        ),
    ]
