# Generated by Django 4.2.7 on 2024-04-23 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_blockchains_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchains',
            name='difficulty_target',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='blockchains',
            name='header',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blockchains',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockchains',
            name='version',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='header',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 33, 32, 300395, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 33, 32, 299733, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='fea901dd1de748a4a90e1fdd5aaff2ba', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='2a49d82cc9884cd1a8df2c6b1c486653', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_wallet',
            field=models.CharField(default='343fd3fe07d54cca8458c22bea94b1e5', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 33, 32, 301122), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 33, 32, 301177), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 1, 33, 32, 301157), null=True),
        ),
    ]
