# Generated by Django 4.2.7 on 2025-01-07 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_transaction_status_sell_alter_account_address_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_wallet',
            field=models.CharField(default='b81962d03a484912b3408943c1b667b0', max_length=200),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 2, 9, 36, 36790, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 2, 9, 36, 40698), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 2, 9, 36, 40827), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 2, 9, 36, 40759), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 2, 9, 36, 35660, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='0c09f8a00d9845339f09d193989b1eda', max_length=200, null=True),
        ),
    ]
