# Generated by Django 4.2.7 on 2024-04-25 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_blockchains_difficulty_target_blockchains_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 41, 49, 879147, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='header',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 41, 49, 878517, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='3ebcfe7266c844feb3e8972039e477d1', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='32e335c06acd4b40be716674f42f049e', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='header',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_wallet',
            field=models.CharField(default='cccb63d481054915a18aa5fad35974e5', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 41, 49, 879726), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 41, 49, 879767), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 41, 49, 879753), null=True),
        ),
    ]
