# Generated by Django 4.2.7 on 2025-01-07 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_account_address_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_wallet',
            field=models.CharField(default='015e2262d35f404a998b27d9442d1875', max_length=200),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 3, 30, 4, 289116, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 3, 30, 4, 290469), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 3, 30, 4, 290519), null=True),
        ),
        migrations.AlterField(
            model_name='blockchainuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 3, 30, 4, 290498), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 3, 30, 4, 288305, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
