# Generated by Django 4.2.7 on 2024-05-07 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_blockchains_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 35, 59, 226141, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='difficulty_target',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 35, 59, 225767, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='56953640f2d04a92aa505c140d23e76d', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='ab81379a90ec4ae08e6995593d0199aa', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_wallet',
            field=models.CharField(default='a609db0f4beb4c21aff490f565378403', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 35, 59, 226506), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 35, 59, 226541), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 35, 59, 226531), null=True),
        ),
    ]
