# Generated by Django 4.2.7 on 2024-05-07 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_blockchains_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 42, 42, 310498, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='header',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 42, 42, 310054, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='7233bacc33124102addd7ef8f8ba1ea6', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='fae0741cc1e94f41a1a4fb3e84510a2b', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='header',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_wallet',
            field=models.CharField(default='536e2070ae4c493d98afba3597f62d5b', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 42, 42, 310861), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 42, 42, 310891), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 14, 42, 42, 310881), null=True),
        ),
    ]
