# Generated by Django 4.2.7 on 2024-05-08 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_blockchains_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchains',
            name='difficulty_target',
        ),
        migrations.RemoveField(
            model_name='blockchains',
            name='nonce',
        ),
        migrations.AlterField(
            model_name='blockchains',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 32, 10, 57151, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 32, 10, 56734, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_key',
            field=models.CharField(default='28019045b8f443779e50af15058dc23f', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_key',
            field=models.CharField(default='1249b85e09454ea78e6f75fda0e5529d', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_wallet',
            field=models.CharField(default='4258ef3f84fd47ad998d951658087b90', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 32, 10, 57476), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 32, 10, 57541), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 32, 10, 57517), null=True),
        ),
    ]
